# Generated by Django 2.2.2 on 2019-06-10 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miriapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.FileField(upload_to=''),
        ),
    ]
